### ISSUE TITLE
Add support for namespaced service names

### ISSUE THREAD

**Issue by goatfryed** [overblog/dataloader-bundle#14]
Service ids with \ are not considered viable services. Since symfony 3.4+ recommends and auto configuring services as their FQCN, you need to introduce an alias to configure batch_load_fn.

To fix this, the `Overblog\DataLoaderBundle\DependencyInjection\Configuration::SERVICE_CALLABLE_NOTATION_REGEX` should be changed. We could use the same capture group definition as for function in `PHP_CALLABLE_NOTATION_REGEX`, i guess.

**Comment by mcg-web** [comment]
Hi, nice catch! Thanks for your feedback. I think, regex will no more be sufficient, we should use compiler pass to test if service exists otherwise fallback to static class notation.

**Comment by akomm** [comment]
It it safe to create own loader service for autowiring & configuration, instead of using your builder, which builds from configuration?

Currently the extension-config-way is wonky. 

- It generates services, which can not be type-hinted for DI in constructor, because they are all of the same type: `Overblog\DataLoader\DataLoader`.
- Therefore you have to either inject the container into the resolver, or manually configure the resolver service.
- It forces you to use non-FQCN service names and configure __actually__ the same piece of logic twice, once for the service which executes the loading and then the DataLoader instance as a service.

I would rather prefer creating either via inheritance or via composition, which can be autowired by being different types.

**Comment by akomm** [comment]
I understand. Thanks for reply.

**Comment by mcg-web** [comment]
fixed in v0.4.1
